name: CI & Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  ci:
    name: Install, Test & SonarQube
    runs-on: windows-latest

    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write

    # roda em push na dev e PRs abertos (nÃ£o no closed)
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action != 'closed')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js v22.11.0
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Run tests & collect coverage
        run: npx vitest run --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccf4f1f0a0249b1d0d0b1d3c5b67c0ea # v6.0.0
        with:
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}


      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b # v1.2.0
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy_vercel:
    name: Deploy to Vercel (Production)
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Deploy SOMENTE quando PR dev -> master for merged
    if: >
      github.event_name == 'pull_request' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'master' &&
      github.event.pull_request.head.ref == 'dev'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --token "$VERCEL_TOKEN"
